### ISSUE TITLE
Sharetool: Voting to allow override any protection

### ISSUE THREAD

**Issue by S-S-X** [S-S-X/metatool#25]
Allow players to vote if some node should be owned by shared account and therefore managed by moderators.

This idea was one possible way to solve conflicts like one where:
- Player 1 added travelnet somewhere
- Player 2 disagree and claim that area is construction site for new city
- Player 2 protects area and player 1 disagrees with that

Who is right here? Depends on exact situation, can be either player 1 or player 2 and there is no direct way to make perfect decision about situation and how to handle it.
However, things already done also is not good situation so something must be done.

Proposal for handling conflicts like this:
- Allow moderators to start voting by using sharetool on protected node
- Moderators or player with certain privileges or xp level can vote to move conflicting nodes to shared account
- Require server admin or at least 2 moderators to close voting and either leave nodes alone or transfer to shared account

This could also be used to remove conflicting areas or protector blocks where action to do so would require more than single moderator to actually make final decision about how things should be in the end.

### To do, break down to separate tasks:
- [ ] Implement basic voting for sharetool #45 
- [ ] Implement chat command registration for metatool API #31 
- [x] Implement wildcard node definitions for metatool API #32
- [ ] Implement actual functionality that uses voting for sharetool
  - [ ] Areas
  - [ ] Protection blocks
  - [ ] Travelnets (add possibility for voting)
- [ ] Allow defining custom parameters for each voting session (required vote count, required result ratio)

**Comment by 6r1d** [comment]
Thanks, I think it is a step in a right direction, at the very least: some people just create accounts, walk a bit, protect something near a city and leave.
(Just look at Mystic.)

**Comment by S-S-X** [comment]
## Selecting any node (allows selecting areas for example)

How this could possibly be integrated into single tool that also has other functions (sharetool):
* Add configuration foor tool registration to accept any node
* Special tool node definition that follows similar rules with current node registration but ignores nodes setting, books for example: https://github.com/S-S-X/metatool/blob/master/sharetool/nodes/book.lua#L30
* While using tool if specific registered node could not be found then use that special definition, this allows for example targeting areas with sharetool. Add exception here if tool has some can_target_anything setting enabled https://github.com/S-S-X/metatool/blob/master/metatool/api.lua#L391

Changes required for API:
* Allow tageting "wildcard" nodes and return special registered wildcard node https://github.com/S-S-X/metatool/blob/master/metatool/api.lua#L391
* Special widlcard node definition must skip checking if node is registered: https://github.com/S-S-X/metatool/blob/master/metatool/api.lua#L346

Special wildcard name for node registration:
* Must not be any registered node name
* Using something like metatool:nodedef_wildcard or metatool:* is probably best option for this

How to register that special wildcard node:
* No need to add another parameter for tool registration
* Just register node with identifier metatool:* and API can check if that exists

## Implementing voting

Not sure if this should go into API or should be implemented specifically for tool.
Both can be done, API only makes sense if it is possible to make this generic enough.

If integrated into API it should then have separate voting API that can be used to start voting, add votes, remove votes, close voting, execute callback action with voting results.

Could be better and easier to create custom voting specifically for sharetool and finish metatool chat command registration API for this so that sharetool can register commands like
```
/sharetool:vote <vote_id> <answer>
/sharetool:vote:close <vote_id>
/sharetool:vote:close <vote_id> <answer>
```

Voting should have possibility to add any number of answers from beginning, not just yep/nope, as this wont add any significant complexity but allows a lot more flexible voting.

**Comment by S-S-X** [comment]
Basic formspec API is done and that could be used to configure voting session: https://github.com/S-S-X/metatool/blob/master/metatool/formspec.lua
