### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by S-S-X** [S-S-X/metatool#62]
After all of the following is done:
- [x] [#61 API refactoring](https://github.com/S-S-X/metatool/pull/61).
  - [x] ~TBD?: Isolate metatool special parameters from tool storage data. (description, group)~
    * Can be included in feature update if API (`copy` function return value/structure) wont change. That would only affect internal data structure.
  - [x] Allow tool/nodedef to somehow inform API that targeted things is not supported by tool even if registered.
    * Probably possible to include in feature update
- [x] [#54 Magic pen](https://github.com/S-S-X/metatool/issues/54).
- [x] [#55 Container tool](https://github.com/S-S-X/metatool/issues/55).
- [ ] [#69 Fix container tool recipe](https://github.com/S-S-X/metatool/issues/69).
- [x] API documentation, at least update existing v1.x methods to reflect changes done.
- [x] Basic testing and review.
  - [x] Automated regression tests for container tool and magic pen.
        :exclamation: basic behavior and protection tests added only for container tool, add tests later if needed.
- [x] Monkey testing (try to utilize pandorabox monkeys if possible :smile:).
- [ ] [#78 Add version information to metatool namespace](https://github.com/S-S-X/metatool/issues/78).
- [x] ContentDB does not handle multiline dependencies in mod.conf https://github.com/minetest/contentdb/issues/243

Bump version to 2.0.0 and create release.

**Comment by S-S-X** [comment]
Other features / updates added after last release
* New tools
  * Digtron configuration tool added.
  * Magic pen added.
  * Container tool added.
* Sharetool updated:
  * Repair some specific problems in travelnet database
  * Transfer node ownership / areas to another player #70 * Formspec API updated, metatool.form.Form added.
  * Added travelnet database validation and repair tool
* Tool API
  * tool.on_read_node is now optional and not required anymore
  * tool.on_write_node is now optional and not required anymore
  * if above functions are not defined then node callbacks will be used directly
  * return nil from copy, paste or info to indicate that tool cannot be used on node

**Comment by S-S-X** [comment]
Breaking changes:
* Configuration
  * Default configuration is exported by default, can be disable through minetest.conf
* Formspec API
  * metatool.form.register_form function signature changed, accepts table instead of 2 mixed type args
  * will not accept raw formspec string anymore, on_create must be function
  * on_create can return metatool.form.Form object, returning Form object will enable nonce security checks
  * metatool.form.Form is still considered unstable preview
* Node registration
  * Dropped sub table from node definition, everything that was in `tooldef` sub table should be moved to top level definition table.
  * Refactored node definition to consistently use OOP style callbacks
    * nodedef:info(node, pos, player, itemstack)
    * nodedef:copy(node, pos, player)
    * nodedef:paste(node, pos, player, tooldata)
  * Defining both tool.copy and tool.paste is not required anymore, it is possible to leave one undefined.
